export const DEPARTMENTS = {
    //--- HOCHIMINH SITE ---
    BOARD_OF_DIRECTOR_HCM: 1000,
    TECHNOLOGY_ADVISORY_BOARD_HCM: 1001,
    HUMAN_RESOURCES_AND_ADMINISTRATOR_HCM: 1002,
    PURCHASING_AND_LOGISTIC_HCM: 1003,
    FINANCE_AND_ACCOUNTING_HCM: 1004,
    ORGANIZING_AND_PLANNING_DEPARTMENT_HCM: 1005,
    MARKETING_HCM: 1006,
    AUTOMATION_AND_ELECTRICAL_SOLUTIONS_SALES_DEPARTMENT_HCM: 1007,
    ACOUNT_MANAGER_HCM: 1008,
    ELECTRICAL_SYSTEM_SALES_TEAM_HCM: 1009,
    AUTOMATION_SALES_TEAM_HCM: 1010,
    PIS_SALES_HCM: 1011,
    INDUSTRY_PRODUCTS_SALES_DEPARTMENT_HCM: 1012,
    ESTEC_DIGITAL_HCM: 1013,
    DIGITAL_SALES_TEAM_HCM: 1014,
    PROJECT_DELIVERY_HCM: 1015,
    RND_TEAM_HCM: 1016,
    ENGINEERING_CONSTRUCTION_SERVICES_DEPARTMENT_HCM: 1017,
    AUTOMATION_TEAM_HCM: 1018,
    ELECTRICAL_TEAM_HCM: 1019,
    INSTRUMENTATION_TEAM_HCM: 1020,
    INDUSTRIAL_SETVICES_TEAM_HCM: 1021,
    M_AND_E_TECHNICIAN_TEAM_HCM: 1022,
    BACK_OFFICE_TEAM_HCM: 1023,
    // --- DANANG SITE ---
    BOARD_OF_DIRECTOR_DN: 2000,
    HUMAN_RESOURCES_AND_ADMINISTRATOR_DN: 2001,
    FINANCE_AND_ACCOUNTING_DN: 2002,
    SALES_DEPARTMENT_DN: 2003,
    AUTOMATION_TEAM_DN: 2004,
    ELECTRICAL_TEAM_DN: 2005,
    INSTRUMENTATION_TEAM_DN: 2006,
    M_AND_E_FLENDER_GEAR_BOXES_REPAIRING_SERVICES_DN: 2007,
    ESTEC_DIGITAL_DN: 2008,
    TRAINING_CENTER_DN: 2009,
    BACK_OFFICE_TEAM_DN: 2010, 
};
// Helper function to get department name
export const getDepartmentName = (deptId) => {
    const entry = Object.entries(DEPARTMENTS).find(([, id]) => id === deptId);
    return entry ? entry[0].replace(/_/g, ' ') : 'Unknow Department';
};